FROM node:22-alpine

WORKDIR /app

COPY package*.json .

RUN npm ci

COPY . .

# npm start is a shortcut for `npm run start`.
# in our case here, we want to run the dev script - where this shortcut does not exist.
CMD ["npm", "run", "dev"]