# largest
#FROM node:22

# way smaller
#FROM node:22-slim

# smallest - least vulnerabilities
FROM node:22-alpine

WORKDIR /app
COPY package*.json .

RUN npm ci

COPY index.js index.js

CMD ["node", "index.js"]