# largest
#FROM node:22

# way smaller
#FROM node:22-slim

# smallest - least vulnerabilities
FROM node:22-alpine

WORKDIR /app
COPY package*.json .

RUN npm ci

# Code is likely to change more often than dependencies, so put it last
COPY index.js index.js

CMD ["node", "index.js"]