# largest
#FROM node:22

# way smaller
#FROM node:22-slim

# smallest - least vulnerabilities
FROM node:22-alpine

WORKDIR /app
COPY package*.json .

# Install only runtime dependencies (not devDependencies)
RUN npm ci  --only=production

# Code is likely to change more often than dependencies, so put it last
COPY index.js index.js

CMD ["node", "index.js"]