#FROM node:22       # largest
#FROM node:22-slim  # way smaller
FROM node:22-alpine # smallest - least vulnerabilities

WORKDIR /app
COPY package*.json .

RUN npm ci

COPY index.js index.js

CMD ["node", "index.js"]